server:
  port: 8080
  host: "localhost"
  read_timeout: "30s"
  write_timeout: "30s"

database:
  path: "./data/market-watch.db"
  max_open_conns: 25
  max_idle_conns: 5
  conn_max_lifetime: "5m"

polygon:
  api_key: "${POLYGON_API_KEY}"
  base_url: "https://api.polygon.io"
  timeout: "30s"
  retry_attempts: 3

collection:
  interval: "5m"
  default_watched_symbols:
    - "PLTR"
    - "TSLA"
    - "BBAI"
    - "MSFT"
    - "NPWR"

logging:
  level: "info"
  format: "json"
  output: "stdout"

data_retention:
  days: 30
  cleanup_interval: "24h"

# Email notification settings (Gmail SMTP)
email:
  smtp_host: "smtp.gmail.com"
  smtp_port: 587
  username: "your-email@gmail.com"
  password: "your-gmail-app-password"
  from_name: "Market Watch"
  from_address: "your-email@gmail.com"
  enabled: true

watchlist_defaults:
  strategies:
    - name: "long long"
      color: "#1e90ff"
      stocks:
        - "NVDA"
        - "PLTR"
        - "TSLA"
    - name: "data centers"
      color: "#28a745"
      stocks:
        - "LTRB"
        - "ANET"
        - "VRT"
        - "CEG"
